"""reflect current models

Revision ID: 3eac5a33f219
Revises: 
Create Date: 2026-06-05 06:33:47.808297
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3eac5a33f219'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subcategory')
    op.drop_index('ix_offer_model_created_at', table_name='offer_model')
    op.drop_index('ix_offer_model_listing_id', table_name='offer_model')
    op.drop_table('offer_model')
    op.drop_index('ix_order_model_created_at', table_name='order_model')
    op.drop_index('ix_order_model_reference', table_name='order_model')
    op.drop_table('order_model')
    op.drop_table('bank_account')
    op.drop_index('ix_listing_model_category', table_name='listing_model')
    op.drop_index('ix_listing_model_created_at', table_name='listing_model')
    op.drop_index('ix_listing_model_seller_id', table_name='listing_model')
    op.drop_index('ix_listing_model_title', table_name='listing_model')
    op.drop_table('listing_model')
    op.drop_table('message')
    op.drop_table('deal_method')
    op.drop_table('offer_legacy_name')
    op.drop_table('offer')
    op.drop_table('payment')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    op.drop_table('chat_session')
    op.drop_index('ix_order_item_model_listing_id', table_name='order_item_model')
    op.drop_index('ix_order_item_model_order_id', table_name='order_item_model')
    op.drop_table('order_item_model')
    op.drop_table('report')
    op.drop_table('review')
    op.drop_table('cart')
    op.drop_table('category')
    op.drop_table('shipping')
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping',
    sa.Column('shippingID', sa.VARCHAR(length=36), nullable=False),
    sa.Column('carrierName', sa.VARCHAR(length=140), nullable=True),
    sa.Column('trackingNumber', sa.VARCHAR(length=140), nullable=True),
    sa.Column('estimatedDeliveryDate', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('shippingID')
    )
    op.create_table('category',
    sa.Column('categoryID', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=140), nullable=False),
    sa.PrimaryKeyConstraint('categoryID')
    )
    op.create_table('cart',
    sa.Column('cartID', sa.VARCHAR(length=36), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('totalPrice', sa.FLOAT(), nullable=False),
    sa.Column('itemCount', sa.INTEGER(), nullable=False),
    sa.Column('items_json', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('cartID')
    )
    op.create_table('review',
    sa.Column('reviewID', sa.VARCHAR(length=36), nullable=False),
    sa.Column('ratingValue', sa.FLOAT(), nullable=False),
    sa.Column('comment', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('reviewID')
    )
    op.create_table('report',
    sa.Column('reportID', sa.VARCHAR(length=36), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), nullable=False),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('received_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['received_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('reportID')
    )
    op.create_table('order_item_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('listing_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=140), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('line_total', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing_model.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_item_model_order_id', 'order_item_model', ['order_id'], unique=False)
    op.create_index('ix_order_item_model_listing_id', 'order_item_model', ['listing_id'], unique=False)
    op.create_table('chat_session',
    sa.Column('chatID', sa.VARCHAR(length=36), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), nullable=False),
    sa.Column('creator_id', sa.INTEGER(), nullable=False),
    sa.Column('buyer_id', sa.INTEGER(), nullable=True),
    sa.Column('seller_id', sa.INTEGER(), nullable=True),
    sa.Column('listing_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('chatID')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('bio', sa.VARCHAR(length=280), nullable=False),
    sa.Column('profile_image', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('legal_name', sa.TEXT(), nullable=True),
    sa.Column('ic_number', sa.TEXT(), nullable=True),
    sa.Column('home_address', sa.TEXT(), nullable=True),
    sa.Column('city', sa.TEXT(), nullable=True),
    sa.Column('region', sa.TEXT(), nullable=True),
    sa.Column('phone_number', sa.TEXT(), nullable=True),
    sa.Column('country', sa.TEXT(), nullable=True),
    sa.Column('last_seen', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.create_table('payment',
    sa.Column('paymentID', sa.VARCHAR(length=36), nullable=False),
    sa.Column('paymentType', sa.VARCHAR(length=80), nullable=False),
    sa.Column('status', sa.VARCHAR(length=80), nullable=False),
    sa.Column('transactionDate', sa.DATETIME(), nullable=True),
    sa.Column('buyer_id', sa.INTEGER(), nullable=True),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('gateway_reference', sa.TEXT(), nullable=True),
    sa.Column('provider', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('paymentID')
    )
    op.create_table('offer',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('listing_id', sa.INTEGER(), nullable=False),
    sa.Column('buyer_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('amount', sa.NUMERIC(), nullable=False),
    sa.Column('message', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer_legacy_name',
    sa.Column('offer_id', sa.INTEGER(), nullable=True),
    sa.Column('legacy_name', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_table('deal_method',
    sa.Column('dealMethodID', sa.VARCHAR(length=36), nullable=False),
    sa.Column('methodType', sa.VARCHAR(length=80), nullable=False),
    sa.Column('carrierName', sa.VARCHAR(length=140), nullable=True),
    sa.Column('meetupLocation', sa.VARCHAR(length=255), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('isDefault', sa.BOOLEAN(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['listing_model.id'], ),
    sa.PrimaryKeyConstraint('dealMethodID')
    )
    op.create_table('message',
    sa.Column('messageID', sa.VARCHAR(length=36), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('creator_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.chatID'], ),
    sa.PrimaryKeyConstraint('messageID')
    )
    op.create_table('listing_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('seller_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=140), nullable=False),
    sa.Column('category', sa.VARCHAR(length=80), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('condition', sa.VARCHAR(length=80), nullable=False),
    sa.Column('location', sa.VARCHAR(length=80), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('kind', sa.VARCHAR(length=20), nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=255), nullable=False),
    sa.Column('seed_image_data', sa.TEXT(), nullable=False),
    sa.Column('tags_csv', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('sku', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listing_model_title', 'listing_model', ['title'], unique=False)
    op.create_index('ix_listing_model_seller_id', 'listing_model', ['seller_id'], unique=False)
    op.create_index('ix_listing_model_created_at', 'listing_model', ['created_at'], unique=False)
    op.create_index('ix_listing_model_category', 'listing_model', ['category'], unique=False)
    op.create_table('bank_account',
    sa.Column('bankAccountNum', sa.VARCHAR(length=64), nullable=False),
    sa.Column('bankName', sa.VARCHAR(length=140), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('bankAccountNum')
    )
    op.create_table('order_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('buyer_name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('buyer_email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=40), nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('fee', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('reference', sa.VARCHAR(length=24), nullable=False),
    sa.Column('note', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_model_reference', 'order_model', ['reference'], unique=False)
    op.create_index('ix_order_model_created_at', 'order_model', ['created_at'], unique=False)
    op.create_table('offer_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('listing_id', sa.INTEGER(), nullable=False),
    sa.Column('buyer_name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_offer_model_listing_id', 'offer_model', ['listing_id'], unique=False)
    op.create_index('ix_offer_model_created_at', 'offer_model', ['created_at'], unique=False)
    op.create_table('subcategory',
    sa.Column('subcategoryID', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=140), nullable=False),
    sa.Column('parent_id', sa.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.categoryID'], ),
    sa.PrimaryKeyConstraint('subcategoryID')
    )
    # ### end Alembic commands ###
    # ### end Alembic commands ###
